# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.46.1"
"ui.nvim" = "1.4.0"
"lualine.nvim" = "scm"
"rocks-config.nvim" = "3.1.2"
catpuccin = "1.11.0"
"kanagawa.nvim" = "scm"
"rocks-git.nvim" = "2.5.6"
"blink.cmp" = { git = "Saghen/blink.cmp", rev = "v1.7.0" }
"mini.nvim" = "0.16.0"
"mason.nvim" = "2.0.1"
"yazi.nvim" = "13.0.0"
"mason-lspconfig.nvim" = "2.1.0"
"gitsigns.nvim" = "1.0.2"
"which-key.nvim" = "3.17.0"
nvim-treesitter-context = "1.0.0"
nvim-web-devicons = "0.100"
"mini.icons" = "0.16.0"

[config]
auto_setup = true
colorscheme = "kanagawa"
