# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.46.1"
"rocks-git.nvim" = "2.5.6"
"rocks-config.nvim" = "3.1.2"
"rocks-lazy.nvim" = "1.2.2"
"rocks-treesitter.nvim" = "1.3.1"

## Tree-sitter parsers
tree-sitter-python = "0.0.46"
tree-sitter-javascript = "0.0.39"
tree-sitter-typescript = "0.0.37"
tree-sitter-html = "0.0.37"
tree-sitter-css = "0.0.38"

# nvim-treesitter-context = "1.0.0"

## lsp, completion
"nvim-lspconfig" = "2.5.0"
"lazydev.nvim" = { version = "scm", ft = "lua" }
nvim-navic = "scm"
"mason.nvim" = "2.0.1"
"mason-lspconfig.nvim" = "2.1.0"
"blink.cmp" = { git = "Saghen/blink.cmp", rev = "v1.7.0" }
nvim-autopairs = "scm"

## UI
nvim-web-devicons = "0.100"
"ui.nvim" = "1.4.0"
"lualine.nvim" = "scm"
"which-key.nvim" = "3.17.0"
"alpha-nvim" = "scm"

## Utilitários
# "mini.nvim" = "0.16.0"
"yazi.nvim" = "13.0.0"
"telescope.nvim" = "scm"
"gitsigns.nvim" = "1.0.2"

## Colorschemes
catpuccin = "1.11.0"
"kanagawa.nvim" = "scm"

## live-preview
"live-preview.nvim" = "0.9.5"

# rocks.toml with rocks-config.nvim installed
#[plugins."fugit2.nvim".config]
#width = 100
#libgit2_path = "libgit2"


[config]
auto_setup = true # executa setup() automaticamente se existir
colorscheme = "kanagawa"
plugins_dir = "plugins" # Lua rocks-config vai buscar configs aqui

[treesitter]
auto_highlight = "all"
auto_install = false
